### ISSUE TITLE
Вебсокеты на Go ("общение" между пользователями в "комнате")

### ISSUE THREAD

**Issue by Alexander-Kints** [antonymofyou/practiceBack#3]
В репозиторий залита простая базовая структура проекта: конфиг, пример http роута, эхо-вебсокет

Задача следующая:

Необходимо научиться создавать комнаты между пользователями и передавать между ними данные. Базу данных на этом этапе использовать не нужно, все данные храним в памяти. Пакет для ws - github.com/gorilla/websocket
Получается, пользователь делает запрос на подключение к ws: он может либо подключиться к существующей комнате, либо создать свою. После того, как комната была создана, к неё могут подключиться другие пользователи. Все данные, которые пользователи отправляют внутри комнате - транслируются другим пользователям

Другими словами - чат между пользователями, где они перекидываются произвольными данными.
Детали реализации не сильно важны, но ты можешь уточнять, как лучше сделать со стороны архитектуры этой задачи
Если будут вопросы по языку - можешь также задавать, будем решать/разбираться вместе

**Comment by fastik1** [comment]
Как уже обсуждали, все данные о комнате берутся из БД по device пользователя

Сейчас уже есть функция getRoomID(), откуда по девайсу имитируется получение ID комнаты. Эта функция (ее можно будет переименовать в getRoom) должна возвращать теперь структуру с полями, где хранятся поля InitiatorDevice (int) и ResponderDevice (int).

После получения данных комнаты с двумя пользователями нам становится доступно определение роли текущего пользователя, либо он initiator, либо он responder. При создании комнаты пользователь записывается в initiator, при подключении к комнате он записывается в responder

Мы должны обеспечить последовательную передачу данных между initiator'ом и responder'ом:

1) initiator при подключении кидает offer, его мы куда-то записываем (в какую-то структуру пользователя)
2) при подключении responder'а отправляем ему offer от initiator'а
3) после чего ждем answer от responder'а и после получения передаем его initiator'у
4) закрываем соединение

Структуру данных нужно будет продумать самому, как-то расширить текущую, т.к. нужно будет хранить промежуточные данные/состояния. Сначала лучше ее продумать, обсудить, и потом технически реализовывать функционал
