### ISSUE TITLE
Сотрудники

### ISSUE THREAD

**Issue by antonymofyou** [antonymofyou/practiceBack#5]
Необходимые таблицы:
staff - сотрудники (ФИО - разбить по полям), (id auto_increment), (vk_id), (blocked), (type)
staff_pers_data (данные из таблицы по картам и прочему)

Методы:
1. Добавление нового сотрудника
2. Удаление сотрудника
3. Редактирование сотрудника
4. Получение из ВК фамилии, имени, айди по ссылке ВК
5. Получение данных о сотруднике

**Comment by fastik1** [comment]
staff_pers_data
Колонки: user_id, field (VARCHAR 255; название поля), value (TEXT, значение поля), comment (TEXT; комментарий)
Индекс primary key на user_id + field, отдельный индекс на user_id

**Comment by fastik1** [comment]
Задача перешла в #43

**Comment by fastik1** [comment]
Новые требования:

Нужно немного поменять сущности. Есть таблица `managers`:
```sql
CREATE TABLE `managers` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_vk_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  INDEX `user_vk_id` (`user_vk_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

До недавних пор она использовалась исключительно для менеджеров в системе HR. Теперь же появилось необходимость добавлять в систему не только менеджеров, но и других сотрудников. Рассматривали вариант ввода третьей таблицы staff, но это накладывает доп. проблемы: нужно создавать третью авторизацию (кандидат, менеджер, сотрудник).
В ходе обсуждения пришли к выводу, что таблица `managers` будет включать не только самих менеджеров, но и других сотрудников. Тип сотрудника будет определяться полем `type` ("Админ", "Менеджер", "Сотрудник").

Сейчас уже готов CRUD для сотрудников (таблиц `staff` и `staff_pers_data`).

Задача следующая:
- перенести этот CRUD на таблицу `managers`, вместо `staff`
- таблицу `staff` нужно удалить
- таблицу `staff_pers_data` нужно переименовать в `managers_pers_data`. Колонку `staff_id` переименовать в `manager_id`

Ключевое - таблица `managers` это теперь не только менеджеры, но и сотрудники
